### ISSUE TITLE
phophlo on IE

### ISSUE THREAD

**Issue by hisakonog** [ProjetDeRechercheSurLecriture/DyslexDisorthGame#263]
just as a record, phophlo on Internet Explorer looks like this: 
![phophlo on ie](https://cloud.githubusercontent.com/assets/760694/5880932/387b8664-a30a-11e4-92a7-46649ef9af7a.PNG)

**Comment by cesine** [comment]
we need phophlo to work on IE on windows 7 or windows 8, and angular is supposed to work on current versions of IE. 

can you tell us more about which version of IE or which version of windows or something?

**Comment by hisakonog** [comment]
Windows 7 and IE version 9.0.34.
